const URL='https://agdmlgbfxoqhztiormij.supabase.co/rest/v1';
const KEY='sb_publishable_8ZPkgNORB1X60ic5LaRWxw_EevahDkr';
const H={apikey:KEY,Authorization:`Bearer ${KEY}`};
const $=id=>document.getElementById(id);
const S={all:[],filtered:[],shown:40,docs:new Map()};
const F=new Intl.DateTimeFormat('en-IN',{day:'2-digit',month:'short',year:'numeric',hour:'2-digit',minute:'2-digit',hour12:true,timeZone:'Asia/Kolkata'});
const FD=new Intl.DateTimeFormat('en-IN',{day:'2-digit',month:'short',year:'numeric',timeZone:'Asia/Kolkata'});
const esc=(v='')=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const hrs=t=>(new Date(t).getTime()-Date.now())/36e5;
const money=v=>v==null?'Not published':'₹'+Number(v).toLocaleString('en-IN',{maximumFractionDigits:0});
const defence=t=>!!t.defence||/army|navy|air force|dg armed|defence|military/i.test(`${t.buyer||''} ${t.title||''}`);
const deadline=t=>(t.deadline_precision==='date_only'||t.closing_time_verified===false)?`${FD.format(new Date(t.deadline))} • time pending`:`${F.format(new Date(t.deadline))} IST`;
async function api(p){const r=await fetch(URL+p,{headers:H,cache:'no-store'});if(!r.ok)throw new Error(`HTTP ${r.status}`);return r.json()}
async function load(){
 $('loadingState').hidden=false;$('errorState').hidden=true;
 try{
  const cols='id,bid_number,title,category,subcategory,buyer,location,published_at,deadline,status,source_url,estimated_value_inr,defence,emd_inr,verification_note,priority,urgency,bid_to_ra,pvms,matched_keywords,deadline_precision,closing_time_verified,analysis_summary,risk_flags,recommended_action,ai_context_note';
  S.all=await api(`/tenders?select=${cols}&status=eq.published&deadline=gt.${encodeURIComponent(new Date().toISOString())}&order=deadline.asc&limit=1000`);
  categories();kpis();filter();
 }catch(e){$('errorState').hidden=false;$('errorState').textContent='Live database could not be loaded. '+e.message}
 finally{$('loadingState').hidden=true}
}
function categories(){const a=[...new Set(S.all.map(t=>t.subcategory||t.category).filter(Boolean))].sort();$('categoryFilter').innerHTML='<option value="">All categories</option>'+a.map(x=>`<option>${esc(x)}</option>`).join('')}
function kpis(){
 $('kpiLive').textContent=S.all.length;
 $('kpiUrgent').textContent=S.all.filter(t=>hrs(t.deadline)<=72).length;
 $('kpiDefence').textContent=S.all.filter(defence).length;
 $('kpiNew17').textContent=S.all.filter(t=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Kolkata'}).format(new Date(t.published_at))==='2026-09-17').length;
}
function filter(){
 const q=$('searchInput').value.trim().toLowerCase(),p=$('priorityFilter').value,c=$('categoryFilter').value,u=$('urgencyFilter').value,d=$('defenceFilter').value,tm=$('timeFilter').value;
 S.filtered=S.all.filter(t=>{const h=hrs(t.deadline),df=defence(t),cat=t.subcategory||t.category,hay=`${t.bid_number} ${t.title} ${t.buyer} ${t.location} ${t.pvms||''} ${t.matched_keywords||''}`.toLowerCase();return(!q||hay.includes(q))&&(!p||(t.priority||'').startsWith(p))&&(!c||cat===c)&&(!u||(u==='critical'&&h<24)||(u==='72'&&h<=72)||(u==='7d'&&h<=168))&&(!d||(d==='yes'&&df)||(d==='no'&&!df))&&(!tm||(tm==='verified'&&t.closing_time_verified!==false&&t.deadline_precision!=='date_only')||(tm==='pending'&&(t.closing_time_verified===false||t.deadline_precision==='date_only')))});
 S.shown=40;render();
}
function card(t){const h=Math.max(0,Math.round(hrs(t.deadline))),risk=(t.risk_flags||[])[0],verified=t.closing_time_verified!==false&&t.deadline_precision!=='date_only';return `<article class="tender-card"><div class="card-top"><div><div class="bid-no">${esc(t.bid_number)}</div><h3>${esc(t.title)}</h3><div class="buyer">${esc(t.buyer)}${t.location?' • '+esc(t.location):''}</div></div><div class="deadline"><strong>${esc(deadline(t))}</strong><small>${h} hours left</small></div></div><div class="badges"><span class="badge ${String(t.priority||'').startsWith('A1')?'a1':String(t.priority||'').startsWith('A2')?'a2':''}">${esc(t.priority||'Healthcare')}</span>${defence(t)?'<span class="badge defence">Defence</span>':''}<span class="badge ${verified?'verified':'pending'}">${verified?'Exact time verified':'Time pending'}</span></div><div class="card-grid"><div class="fact"><span>Category</span><strong>${esc(t.subcategory||t.category)}</strong></div><div class="fact"><span>Bid value</span><strong>${money(t.estimated_value_inr)}</strong></div><div class="fact"><span>EMD</span><strong>${money(t.emd_inr)}</strong></div><div class="fact"><span>Published</span><strong>${FD.format(new Date(t.published_at))}</strong></div></div>${risk?`<div class="risk-line">⚠ ${esc(risk)}</div>`:''}<div class="card-actions"><button class="btn primary" onclick="openBid('${t.id}')">View intelligence</button><a class="btn ghost" href="${esc(t.source_url)}" target="_blank" rel="noopener">Official source ↗</a><button class="btn ai" onclick="askBid('${t.id}')">✦ Ask Bid AI</button></div></article>`}
function render(){$('resultCount').textContent=`${S.filtered.length} opportunities • sorted by closing date`;$('tenderList').innerHTML=S.filtered.slice(0,S.shown).map(card).join('')||'<div class="error-card">No live opportunities match these filters.</div>';$('loadMoreBtn').hidden=S.shown>=S.filtered.length}
async function docs(id){if(S.docs.has(id))return S.docs.get(id);const d=await api(`/tender_documents?select=kind,title,official_url,link_status&tender_id=eq.${id}&order=kind.asc`);S.docs.set(id,d);return d}
const byId=id=>S.all.find(t=>t.id===id);
window.openBid=async id=>{const t=byId(id),d=await docs(id);if(!t)return;$('detailBidNo').textContent=t.bid_number;$('detailTitle').textContent=t.title;$('detailBody').innerHTML=`<section class="detail-section"><h3>Decision summary</h3><div class="detail-summary">${esc(t.analysis_summary||'Analysis pending direct specification review.')}</div></section><section class="detail-section"><h3>Closing & verification</h3><div class="card-grid"><div class="fact"><span>Closing</span><strong>${esc(deadline(t))}</strong></div><div class="fact"><span>Priority</span><strong>${esc(t.priority||'—')}</strong></div><div class="fact"><span>Bid to RA</span><strong>${esc(t.bid_to_ra||'Not verified')}</strong></div><div class="fact"><span>Value</span><strong>${money(t.estimated_value_inr)}</strong></div></div></section>${(t.risk_flags||[]).length?`<section class="detail-section"><h3>Risk flags</h3><div class="detail-risk">${t.risk_flags.map(r=>`<span class="badge pending">${esc(r)}</span>`).join('')}</div></section>`:''}${t.recommended_action?`<section class="detail-section"><h3>Next action</h3><div class="detail-summary">${esc(t.recommended_action)}</div></section>`:''}<section class="detail-section"><h3>Official documents</h3><div class="doc-grid">${d.map(x=>`<a class="doc-link" href="${esc(x.official_url)}" target="_blank" rel="noopener"><span>${esc(x.title||x.kind)}</span><strong>Open ↗</strong></a>`).join('')||'<div class="detail-summary">Direct attachments are still being recovered.</div>'}</div></section><section class="ai-panel"><h3>Ask this bid with AI</h3><p>Open ChatGPT with this bid number and its official document links.</p><button class="btn" onclick="askBid('${t.id}')">✦ Ask about this bid</button></section>`;$('bidDialog').showModal()};
window.askBid=async id=>{const t=byId(id);if(!t)return;let d=[];try{d=await docs(id)}catch{}const links=[t.source_url,...d.map(x=>x.official_url)].filter(Boolean);const text=`Read and analyze GeM Bid ${t.bid_number}: ${t.title}. Buyer: ${t.buyer}. Closing: ${deadline(t)}. Read the official links before answering. Do not invent missing facts. Explain eligibility, turnover/experience, MSME relaxations, EMD/ePBG, OEM authorization, Make in India, Bid-to-RA, specifications, required documents, restrictive clauses, risks, possible OEM matches and next actions. Official links:\n${links.join('\n')}`;window.open('https://chatgpt.com/?q='+encodeURIComponent(text),'_blank','noopener')};
$('searchInput').addEventListener('input',filter);['priorityFilter','categoryFilter','urgencyFilter','defenceFilter','timeFilter'].forEach(id=>$(id).addEventListener('change',filter));$('clearFilters').onclick=()=>{$('searchInput').value='';['priorityFilter','categoryFilter','urgencyFilter','defenceFilter','timeFilter'].forEach(id=>$(id).value='');filter()};$('loadMoreBtn').onclick=()=>{S.shown+=40;render()};$('refreshBtn').onclick=load;$('closeDialog').onclick=()=>$('bidDialog').close();document.addEventListener('keydown',e=>{if(e.key==='/'&&document.activeElement.tagName!=='INPUT'){e.preventDefault();$('searchInput').focus()}});load();